Razor CRUD/Razor CRUD/Pages/Employees/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Razor_CRUD.Data;
using Razor_CRUD.Model.Domain;
using Razor_CRUD.Model.View;

namespace Razor_CRUD.Pages.Employees
{
    public class AddModel : PageModel
    {
        private readonly Db db;

        public AddModel(Db db)
        {
            this.db = db;
        }
        [BindProperty]
        public AddEmployee AddEmployeeRequest { get; set; }
        public void OnGet()
        {
        }

        public void OnPost()
        {
            //coverting view to domain
            var employees = new Employee
            {
                Name = AddEmployeeRequest.Name,
                Email = AddEmployeeRequest.Email,
                Salary = AddEmployeeRequest.Salary,
                DateOfBirth = AddEmployeeRequest.DateOfBirth,
                Department = AddEmployeeRequest.Department
            };
            db.Employees.Add(employees);
            db.SaveChanges();
            ViewData["Message"] = "Updated Successfully!";
        }
    }
}

Razor CRUD/Razor CRUD/Pages/Employees/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_CRUD.Data;
using Razor_CRUD.Model.Domain;
using Razor_CRUD.Model.View;
using System.Data;

namespace Razor_CRUD.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly Db db;
        [BindProperty]
        public EditEmployee editEmployee { get; set; }
        public EditModel(Db db)
        {
            this.db = db;
        }
        public void OnGet(Guid id)
        {
            var employee = db.Employees.Find(id);
            if (employee != null)
            {
                //convert domain model to view model
                editEmployee = new EditEmployee()
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    Email = employee.Email,
                    Salary = employee.Salary,
                    DateOfBirth = employee.DateOfBirth,
                    Department = employee.Department
                };
            }
        }

        public void OnPostUpdate()
        {
            //covert view to domain model
            if(editEmployee != null)
            {
                var update = db.Employees.Find(editEmployee.Id);
                if(update != null)
                {
                    update.Name = editEmployee.Name;
                    update.Salary = editEmployee.Salary;
                    update.Email = editEmployee.Email;
                    update.DateOfBirth = editEmployee.DateOfBirth;
                    update.Department = editEmployee.Department;

                    db.SaveChanges();
                    ViewData["Message"] = "Successful!";
                }
            }
        }

        public IActionResult OnPostDelete()
        {
            var delete = db.Employees.Find(editEmployee.Id);
            if(delete != null)
            {
                db.Employees.Remove(delete);
                db.SaveChanges();
                return RedirectToPage("/Employees/List");
            }
            return Page();
        }
    }
}

Razor CRUD/Razor CRUD/Pages/Employees/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_CRUD.Data;
using Razor_CRUD.Model.Domain;

namespace Razor_CRUD.Pages.Employees
{
    public class ListModel : PageModel
    {
        private readonly Db db;
        public List<Employee> employees { get; set; }
        public ListModel(Db db)
        {
            this.db = db;
        }
        public void OnGet()
        {
            employees = db.Employees.ToList();
        }
    }
}

Razor CRUD/Razor CRUD/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Razor_CRUD.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Razor CRUD/Razor CRUD/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor_CRUD.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Razor CRUD/Razor CRUD/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor_CRUD.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Razor CRUD/Razor CRUD/Pages/Employees/Add.cshtml
@page
@model Razor_CRUD.Pages.Employees.AddModel
@{
    var message = ViewData["Message"]?.ToString();
}

<h1 class="mb-3">Add New Employee</h1>
@if(!string.IsNullOrWhiteSpace(message))
{
    <div class="alert alert-success" role="alert">
        @message
    </div>
}
<form method="POST">
<div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" class="form-control" asp-for="AddEmployeeRequest.Name"/>
</div>
<div class="mb-3">
    <label class="form-label">Email</label>
    <input type="text" class="form-control" asp-for="AddEmployeeRequest.Email" />
</div>
<div class="mb-3">
    <label class="form-label">Salary</label>
    <input type="number" class="form-control" asp-for="AddEmployeeRequest.Salary"/>
</div>
<div class="mb-3">
    <label class="form-label">DateOfBirth</label>
    <input type="date" class="form-control" asp-for="AddEmployeeRequest.DateOfBirth"/>
</div>
<div class="mb-3">
    <label class="form-label">Department</label>
    <input type="text" class="form-control" asp-for="AddEmployeeRequest.Department"/>
</div>
<div class="mb-3">
    <button class="btn btn-primary">Save</button>
</div>
</form>

Razor CRUD/Razor CRUD/Pages/Employees/Edit.cshtml
@page "{id:Guid}"
@model Razor_CRUD.Pages.Employees.EditModel
@{
    var message = ViewData["Message"]?.ToString();
}
<h1 class="mb-3">Edit Employee</h1>
@if(!string.IsNullOrWhiteSpace(message))
{
    <div class="alert alert-success" role="alert">
        @message
    </div>
}
<form method="post">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="editEmployee.Id" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="editEmployee.Name" />
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="text" class="form-control" asp-for="editEmployee.Email" />
    </div>
    <div class="mb-3">
        <label class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="editEmployee.Salary" />
    </div>
    <div class="mb-3">
        <label class="form-label">DateOfBirth</label>
        <input type="date" class="form-control" asp-for="editEmployee.DateOfBirth" />
    </div>
    <div class="mb-3">
        <label class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="editEmployee.Department" />
    </div>
    <div class="mb-3 d-flex justify-content-between">
        <button class="btn btn-primary" asp-page-handler="Update">
            Update
        </button>

        <button class="btn btn-danger" asp-page-handler="Delete">
            Delete
        </button>
    </div>
</form>

Razor CRUD/Razor CRUD/Pages/Employees/List.cshtml
@page
@model Razor_CRUD.Pages.Employees.ListModel
@{
}

<h1 class="mb-3">List of Employees</h1>
@if(Model.employees != null && Model.employees.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Salary</th>
                <th>DateOfBirth</th>
                <th>Department</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var i in Model.employees)
            {
                <tr>
                    <td>@i.Id</td>
                    <td>@i.Name</td>
                    <td>@i.Email</td>
                    <td>@i.Salary</td>
                    <td>@i.DateOfBirth</td>
                    <td>@i.Department</td>
                    <td>
                        <a href="/Employees/Edit/@i.Id" class="btn btn-dark">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No Employees found!</p>
}

Razor CRUD/Razor CRUD/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Razor CRUD/Razor CRUD/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Razor_CRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Razor_CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Employees/Add">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Employees/List">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Razor_CRUD - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>